export const Copy = {
  GAME_RUNNING: "PLAYING",
  GAME_PAUSED: "[[ PAUSED ]]",
  HELLO: (name: string) => `Hello ${name}!`,
  NO: "No!",
  SIGN_OUT: "Sign Out!",
  SIGN_OUT_CONFIRM: "Are you sure you want to sign out?",
  SIGN_IN: "Sign In!",
  SIGN_UP: "Sign Up!",
  VIEW_PROFILE: "View account",
  VIEW_LANDING: "Back to landing",
  WELCOME: "Welcome!",
  WELCOME_BACK: (name: string) => `Welcome back ${name}!`,
  YES: "Yes!",
};
